Update terraform-devops.yml

diff --git a/.github/workflows/terraform-devops.yml b/.github/workflows/terraform-devops.yml
--- a/.github/workflows/terraform-devops.yml
+++ b/.github/workflows/terraform-devops.yml
@@ -72,16 +72,6 @@ jobs:
         working-directory: ${{ env.WORKING_DIRECTORY }}
 
     steps:
-      - name: Debug Token
-        run: |
-          echo "TF_TOKEN_app_terraform_io=${TF_TOKEN_app_terraform_io}"
-          if [ -z "${TF_TOKEN_app_terraform_io}" ]; then
-            echo "Error: TF_TOKEN_app_terraform_io is empty. Canceling execution."
-            exit 1
-          else
-            echo "TF_TOKEN_app_terraform_io=${TF_TOKEN_app_terraform_io}"
-          fi
-
       # Checkout the repository to the GitHub Actions runner
       - name: Checkout
         uses: actions/checkout@v2
@@ -103,6 +93,16 @@ jobs:
             az account show
             az storage -h
 
+      - name: Debug Token
+        run: |
+          echo "TF_TOKEN_app_terraform_io=${TF_TOKEN_app_terraform_io}"
+          if [ -z "${TF_TOKEN_app_terraform_io}" ]; then
+            echo "Error: TF_TOKEN_app_terraform_io is empty. Canceling execution."
+            exit 1
+          else
+            echo "TF_TOKEN_app_terraform_io=${TF_TOKEN_app_terraform_io}"
+          fi
+          
       # Install the latest version of Terraform CLI
       - name: Install Terraform
         uses: hashicorp/setup-terraform@v3.1.0
